theme: jekyll-theme-minimal
title: Sam Betts' Portfolio
author: Sam Betts
description: You will find on this website a condensed version of me including the projects I've worked on in the past, my resume, and my contact information
logo: /assets/img/Sam2.jpg
